---
id: web-search-2010
base_name: web-search-technique-for-users
tags:
- rabbit
- web
- search
presentation_date: 2013/06/24
version: 2013.6.24.1
licenses:
- CC BY-SA 3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
